
package org.gov.permit.electricalservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PermitElectricalService", targetNamespace = "urn:permit.gov.org:electricalservice", wsdlLocation = "file:/home/jfroehli/homework/gov-services/electrical-service/src/main/webapp/wsdl/PermitElectricalService.wsdl")
public class PermitElectricalService
    extends Service
{

    private final static URL PERMITELECTRICALSERVICE_WSDL_LOCATION;
    private final static WebServiceException PERMITELECTRICALSERVICE_EXCEPTION;
    private final static QName PERMITELECTRICALSERVICE_QNAME = new QName("urn:permit.gov.org:electricalservice", "PermitElectricalService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/jfroehli/homework/gov-services/electrical-service/src/main/webapp/wsdl/PermitElectricalService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERMITELECTRICALSERVICE_WSDL_LOCATION = url;
        PERMITELECTRICALSERVICE_EXCEPTION = e;
    }

    public PermitElectricalService() {
        super(__getWsdlLocation(), PERMITELECTRICALSERVICE_QNAME);
    }

    public PermitElectricalService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERMITELECTRICALSERVICE_QNAME, features);
    }

    public PermitElectricalService(URL wsdlLocation) {
        super(wsdlLocation, PERMITELECTRICALSERVICE_QNAME);
    }

    public PermitElectricalService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERMITELECTRICALSERVICE_QNAME, features);
    }

    public PermitElectricalService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PermitElectricalService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PermitElectricalServiceInterface
     */
    @WebEndpoint(name = "PermitElectricalServiceInterfaceImplPort")
    public PermitElectricalServiceInterface getPermitElectricalServiceInterfaceImplPort() {
        return super.getPort(new QName("urn:permit.gov.org:electricalservice", "PermitElectricalServiceInterfaceImplPort"), PermitElectricalServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PermitElectricalServiceInterface
     */
    @WebEndpoint(name = "PermitElectricalServiceInterfaceImplPort")
    public PermitElectricalServiceInterface getPermitElectricalServiceInterfaceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:permit.gov.org:electricalservice", "PermitElectricalServiceInterfaceImplPort"), PermitElectricalServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERMITELECTRICALSERVICE_EXCEPTION!= null) {
            throw PERMITELECTRICALSERVICE_EXCEPTION;
        }
        return PERMITELECTRICALSERVICE_WSDL_LOCATION;
    }

}
