
package org.gov.permit.structuralservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PermitStructuralService", targetNamespace = "urn:permit.gov.org:structuralservice", wsdlLocation = "file:/home/jfroehli/homework/gov-services/structural-service/src/main/webapp/wsdl/PermitStructuralService.wsdl")
public class PermitStructuralService
    extends Service
{

    private final static URL PERMITSTRUCTURALSERVICE_WSDL_LOCATION;
    private final static WebServiceException PERMITSTRUCTURALSERVICE_EXCEPTION;
    private final static QName PERMITSTRUCTURALSERVICE_QNAME = new QName("urn:permit.gov.org:structuralservice", "PermitStructuralService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/jfroehli/homework/gov-services/structural-service/src/main/webapp/wsdl/PermitStructuralService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERMITSTRUCTURALSERVICE_WSDL_LOCATION = url;
        PERMITSTRUCTURALSERVICE_EXCEPTION = e;
    }

    public PermitStructuralService() {
        super(__getWsdlLocation(), PERMITSTRUCTURALSERVICE_QNAME);
    }

    public PermitStructuralService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERMITSTRUCTURALSERVICE_QNAME, features);
    }

    public PermitStructuralService(URL wsdlLocation) {
        super(wsdlLocation, PERMITSTRUCTURALSERVICE_QNAME);
    }

    public PermitStructuralService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERMITSTRUCTURALSERVICE_QNAME, features);
    }

    public PermitStructuralService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PermitStructuralService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PermitStructuralServiceInterface
     */
    @WebEndpoint(name = "PermitStructuralServiceInterfaceImplPort")
    public PermitStructuralServiceInterface getPermitStructuralServiceInterfaceImplPort() {
        return super.getPort(new QName("urn:permit.gov.org:structuralservice", "PermitStructuralServiceInterfaceImplPort"), PermitStructuralServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PermitStructuralServiceInterface
     */
    @WebEndpoint(name = "PermitStructuralServiceInterfaceImplPort")
    public PermitStructuralServiceInterface getPermitStructuralServiceInterfaceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:permit.gov.org:structuralservice", "PermitStructuralServiceInterfaceImplPort"), PermitStructuralServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERMITSTRUCTURALSERVICE_EXCEPTION!= null) {
            throw PERMITSTRUCTURALSERVICE_EXCEPTION;
        }
        return PERMITSTRUCTURALSERVICE_WSDL_LOCATION;
    }

}
